#!/usr/bin/env ruby

require_relative './lib'
include Zipography

abort "Usage: #{File.basename __FILE__} old.zip blob > new.zip" if ARGV.size < 2

z = MyZip.new ARGV[0]
data = blob_make ARGV[1]
z.repack(data).each {|buf| $stdout.write buf }
