#!/usr/bin/env ruby

require_relative './lib'
include Zipography

output = options 'file.zip [-o blob]', 1

eocd = eocd_parse ARGV[0], eocd_position(ARGV[0])

File.open(ARGV[0], 'rb') do |f|
  f.seek eocd[:cd_offset_start] - HIDDEN_BLOB_HEADER_SIZE
  header = HiddenBlobHeader.read f

  # validate
  exit 1 unless hbh_validate header
  start_location = eocd[:cd_offset_start] - HIDDEN_BLOB_HEADER_SIZE - header.len
  checksum = adler32_file_slice ARGV[0], start_location, header.len
  exit 1 unless checksum == header[:checksum]

  f.seek start_location
  IO.copy_stream f, output, header.len
end
