#!/usr/bin/env ruby

require_relative './lib'
include Zipography

alien = Alien.new $stdin
puts "Blob size:    #{alien.size}"
puts "Checksum:     0x#{alien.checksum.to_s 16}"
puts "Valid:        #{alien.valid}"
